# Generated by Django 4.0.5 on 2022-11-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=30)),
                ('anio', models.PositiveSmallIntegerField()),
                ('genero', models.PositiveSmallIntegerField()),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
