# Generated by Django 4.0.5 on 2022-11-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0005_alter_genero_nombre_alter_libro_anio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='estado',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
